/**
 * The prose of the generated license documents.
 *
 * Kept apart from the generator so prose claims and computed inventory can be reviewed
 * independently. Identity comes from package.json so a derived app describes itself.
 */

export const NOTICES_INTRO = `
This is the attribution appendix to [\`THIRD_PARTY_LICENSES.md\`](./THIRD_PARTY_LICENSES.md).

The summary document says which licenses are involved. This one reproduces, for every package
in the conservative **production closure** (backend runtime dependencies, frontend bundle
inputs, and their transitive dependencies), the license text and any \`NOTICE\` file the package
itself ships. Optional packages resolved by the lockfile can make this appendix larger than the
Linux image's package directory, never smaller. That is what MIT, BSD, ISC, Apache-2.0 and OFL each
require a redistributor to pass on: not only the license identifier, but the package's own
copyright line and terms when the package supplies them.

This file is copied into the local verification image. Generated by \`bun run licenses:generate\`; do
not edit by hand.
`;

export const intro = (APP: string, LICENSE: string) => `
${APP} is licensed under the [${LICENSE} License](./LICENSE). This document records the license
inventory of the npm dependencies declared by this repository, and carries notice,
source-location, and relink information for the Bun runtime in the local verification image (see "Bundled runtime:
Bun and its LGPL components" below). Package-specific npm terms are reproduced in
[\`THIRD_PARTY_NOTICES.md\`](./THIRD_PARTY_NOTICES.md). Runtime license texts, the Alpine package
inventory, and downstream distribution guidance live in [\`licenses/\`](./licenses). These files
are copied into the local verification image and remain available to derived projects.

Read the scope limits below before treating this as a complete notice for the image: it
enumerates the *direct* production npm dependencies and summarizes the rest of the npm graph
by license family, and it does not inventory the Alpine base system.
`;

export const GROUPS = [
	{ title: 'Backend runtime dependencies', workspaces: ['.', 'backend', 'shared'] },
	{ title: 'Frontend runtime dependencies', workspaces: ['frontend'] },
];

export const scopeSections = (BUN_VERSION: string, APP: string, LICENSE: string) => [
	{
		body: `
The local verification image is built on \`oven/bun:${BUN_VERSION}-alpine\`, so it contains the Bun
runtime, and Bun statically links libraries under the LGPL. This section records what a derived
project must consider before distributing that image. Bun's own license text is reproduced in
[\`licenses/BUN-LICENSE.md\`](./licenses/BUN-LICENSE.md); that file, this file, and the root
\`LICENSE\` are copied into every local build.

${APP} does not publish or offer its verification images. A derived project that distributes
one must provide its own corresponding-source and relink-materials fulfillment. The checklist in
[\`licenses/CONTAINER-DISTRIBUTION.md\`](./licenses/CONTAINER-DISTRIBUTION.md) is guidance, not an
offer by NomadicDaddy.

**LGPL components linked into the Bun runtime**

| Component | License | Full text |
| --------- | ------- | --------- |
| JavaScriptCore / WebKit (including WebCore files) | LGPL-2 | [\`licenses/LGPL-2.0.txt\`](./licenses/LGPL-2.0.txt) |
| TinyCC | LGPL-2.1 | [\`licenses/LGPL-2.1.txt\`](./licenses/LGPL-2.1.txt) |

Bun statically links many other libraries under permissive terms (BoringSSL, brotli,
libarchive, mimalloc, zstd, simdutf, c-ares, libicu, zlib-ng and others), listed with their
licenses in \`licenses/BUN-LICENSE.md\`.

**Upstream source locations**

- The patched WebKit/JavaScriptCore that Bun links is published at
  <https://github.com/oven-sh/webkit>.
- Bun itself (MIT) is at <https://github.com/oven-sh/bun>, tagged \`bun-v${BUN_VERSION}\`.
- TinyCC is at <https://github.com/tinycc/tinycc>.

**How to modify the LGPL library and relink**

Bun is not statically linked into the application here: it is the interpreter the image runs,
supplied by the base image and dynamically replaceable. A downstream recipient who wants a modified
JavaScriptCore can build a modified Bun (\`git submodule update --init --recursive\`,
\`make jsc\`, \`zig build\`, per Bun's LICENSE.md), install it over the runtime in the image, or
rebuild the image with a base image containing it. ${APP}'s own source is ${LICENSE}, so nothing
here restricts that. A downstream distributor must preserve exact corresponding source rather
than rely on these upstream locations remaining unchanged.
`,
		heading: 'Bundled runtime: Bun and its LGPL components',
	},
	{
		body: `
Scope limits of the tables above, recorded rather than left implicit:

- **Transitive npm packages are not enumerated.** The tables list direct production
  dependencies only; the rest of the npm graph appears as license-family counts. The image
  copies the whole installed tree, so transitive packages are included too, and their
  individual attribution notices are not reproduced here.
- **Build and development tooling is not inventoried.** It is not included: the image
  installs production dependencies only.
- **The closure is resolved from the lockfile.** It conservatively covers backend runtime
  packages and frontend bundle inputs; optional packages the lockfile records can make its
  count larger than the exact Linux image package-directory count.
- **MPL-2.0 \`lightningcss\` is build-time only and is not in the image.** The image installs
  production dependencies only. If \`lightningcss\` enters the image, MPL-2.0 requires recipients
  of executable-form distribution to be told where the source is:
  <https://github.com/parcel-bundler/lightningcss>.

What the local verification image actually contains is checked against the built image, not inferred:

- Per-package copyright lines, license text and \`NOTICE\` files for the whole runtime closure
  are reproduced in [\`THIRD_PARTY_NOTICES.md\`](./THIRD_PARTY_NOTICES.md).
- \`bun run check:image-licenses\` opens the built image and fails if any npm package inside it
  is missing from that appendix, or if the notices are not present in the image.
- The operating-system packages are inventoried in
  [\`licenses/base-image-packages.md\`](./licenses/base-image-packages.md), read from the image's
  own apk database.

Both files are present inside the image, alongside \`LICENSE\` and this document.

The base image contains GPL-licensed programs (busybox, apk-tools, gettext and others). They
are unmodified operating-system components alongside the application, not libraries
linked into it. Their exact package versions are recorded in the base-image inventory. GPL and
LGPL license texts plus downstream guidance are included in \`licenses/\`; Alpine's upstream
source is published at <https://gitlab.alpinelinux.org/alpine/aports>.
`,
		heading: 'Scope and what is verified',
	},
];

export interface GeneratedDocuments {
	notices: string;
	summary: string;
}
