/**
 * Reads a built container image and renders the inventory of what its base operating system
 * contributes.
 *
 * Everything here needs a docker daemon and an image that already exists, which is what separates
 * it from the rest of this directory: the other modules answer questions about the lockfile and the
 * development tree, and can run in `smoke:qc`. These answer questions about the artifact, and only
 * run in the docker smoke modes.
 */

import { exit } from 'node:process';

/** Runs a shell script inside the image and returns its stdout, failing loudly on a nonzero exit. */
export async function runInImage(image: string, script: string): Promise<string> {
	const proc = Bun.spawn(['docker', 'run', '--rm', '--entrypoint', 'sh', image, '-c', script], {
		env: { ...process.env },
		stderr: 'pipe',
		stdout: 'pipe',
	});
	const stdout = await new Response(proc.stdout).text();
	const code = await proc.exited;
	if (code !== 0) {
		const stderr = await new Response(proc.stderr).text();
		console.error(`docker run failed against ${image}:`);
		console.error(stderr.trim() || stdout.trim());
		exit(1);
	}
	return stdout;
}

/** Reads name, version and license of every apk package from the image's package database. */
export async function collectBasePackages(image: string): Promise<string[]> {
	const output = await runInImage(
		image,
		'awk -F: \'/^P:/{p=$2} /^V:/{v=$2} /^L:/{print p "|" v "|" $2}\' /lib/apk/db/installed',
	);
	return output
		.split('\n')
		.map((line) => line.trim())
		.filter(Boolean)
		.sort();
}

/**
 * Every npm package directory present in the image, read from bun's store directory names.
 * This is the exact installed runtime set. The conservative closure remains broader because it
 * also covers frontend bundle inputs without package directories in the final image.
 */
export async function collectImagePackages(image: string): Promise<string[]> {
	const output = await runInImage(image, 'ls /app/node_modules/.bun 2>/dev/null || true');
	return (
		output
			.split('\n')
			.map((line) => line.trim())
			.filter((line) => line.includes('@') && !line.startsWith('.'))
			// bun encodes scoped names as @scope+name@version; normalise to @scope/name@version.
			.map((entry) => entry.replace('+', '/'))
			.sort()
	);
}

/** Bun's store directory name for a package: `@scope/name@version` becomes `@scope+name@version`. */
export function storeDirName(entry: string): string {
	return entry.replace('/', '+');
}

export function renderInventory(packages: string[]): string {
	const rows = packages.map((entry) => {
		const [name, version, license] = entry.split('|');
		return `| ${name} | ${version} | ${license || 'UNKNOWN'} |`;
	});

	const copyleft = packages.filter((entry) => /GPL/i.test(entry.split('|')[2] ?? ''));

	return [
		'# Base image packages',
		'',
		'Operating-system packages present in the local production-shaped container image, read from',
		"the image's own apk database. Generated by `bun run licenses:image`; do not edit by hand.",
		'',
		`The image is built on the Bun Alpine base image and contains **${packages.length}** apk`,
		'packages. These are unmodified components of the base operating system included',
		'alongside the application rather than linked into it. The local verification image carries',
		'the applicable GPL/LGPL texts and downstream guidance in',
		'[`CONTAINER-DISTRIBUTION.md`](./CONTAINER-DISTRIBUTION.md). Alpine publishes source at',
		'<https://gitlab.alpinelinux.org/alpine/aports>.',
		'',
		'## Copyleft packages in the image',
		'',
		`**${copyleft.length}** of them carry a GPL-family license (busybox and friends are the`,
		'usual ones). They are separate programs in the same image, not libraries linked into the',
		'application. Their licenses apply to those components rather than the application code.',
		'',
		...copyleft.map((entry) => {
			const [name, version, license] = entry.split('|');
			return `- \`${name}@${version}\` (${license})`;
		}),
		'',
		'## All base image packages',
		'',
		'| Package | Version | License |',
		'| ------- | ------- | ------- |',
		...rows,
		'',
	].join('\n');
}
