#!/usr/bin/env bun
/**
 * Checks spernakit.psd1's per-app versions against each app's own package.json.
 *
 * The manifest is gitignored and nothing read it, so it drifted silently and was believed anyway.
 * It marked a live app 'latest' — the value meaning archived, pending rebuild — and ran a version
 * or more stale on several others; a minority of entries were correct. A manifest that is wrong is
 * worse than one that is missing, because it gets trusted: an upgrade nearly took its base version
 * from here rather than from the app.
 *
 * package.json is the authority here because it is tracked, and because the sync tooling already
 * reads it. This script only reports; it never edits the manifest.
 *
 * Skips apps whose directory is absent (the manifest is fleet-wide, a checkout usually is not) and
 * apps marked 'latest', which is a real state meaning the app is archived pending a rebuild.
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { cwd, exit } from 'node:process';

interface Entry {
	manifestVersion: string;
	slug: string;
}

/**
 * Extracts each app's spernakit_version from the psd1. A real PowerShell parse would need
 * PowerShell; the file's shape is fixed and generated by hand, so a scan is enough and keeps this
 * runnable under plain Bun.
 */
function parseManifest(text: string): Entry[] {
	const entries: Entry[] = [];
	let slug: null | string = null;
	for (const line of text.split('\n')) {
		const slugMatch = /^\s*'([a-z0-9-]+)'\s*=\s*@\{/.exec(line);
		if (slugMatch?.[1] !== undefined) {
			slug = slugMatch[1];
			continue;
		}
		const versionMatch = /^\s*spernakit_version\s*=\s*'([^']+)'/.exec(line);
		if (versionMatch?.[1] !== undefined && slug !== null) {
			entries.push({ manifestVersion: versionMatch[1], slug });
			slug = null;
		}
	}
	return entries;
}

function readAppVersion(appRoot: string): null | string {
	const pkgPath = join(appRoot, 'package.json');
	if (!existsSync(pkgPath)) return null;
	try {
		const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { spernakit_version?: string };
		return pkg.spernakit_version ?? null;
	} catch {
		return null;
	}
}

function main(): void {
	const root = resolve(cwd());
	const manifestPath = join(root, 'spernakit.psd1');
	if (!existsSync(manifestPath)) {
		console.log('No spernakit.psd1 present; nothing to check.');
		return;
	}

	const applications = dirname(root);
	const problems: string[] = [];
	const skipped: string[] = [];

	for (const entry of parseManifest(readFileSync(manifestPath, 'utf8'))) {
		if (entry.manifestVersion === 'latest') continue;
		const appRoot = join(applications, entry.slug);
		const actual = readAppVersion(appRoot);
		if (actual === null) {
			skipped.push(entry.slug);
			continue;
		}
		if (actual !== entry.manifestVersion) {
			problems.push(
				`  - ${entry.slug}: manifest says ${entry.manifestVersion}, package.json says ${actual}`
			);
		}
	}

	if (skipped.length > 0) {
		console.warn(`Not checked (no checkout): ${skipped.join(', ')}`);
	}

	if (problems.length > 0) {
		console.error('spernakit.psd1 disagrees with the apps it describes:');
		for (const problem of problems) console.error(problem);
		console.error(
			'package.json is tracked and is the authority. Update the manifest to match.'
		);
		exit(1);
	}

	console.log('spernakit.psd1 matches every app it describes.');
}

main();
