import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { configLogger } from './configLogger.ts';
import { isPlainObject, projectRoot } from './configUtils.ts';

/**
 * Split-secrets file: `config/{slug}.secrets.json`.
 *
 * The main config (`config/{slug}.json`) carries the app's own cryptographic material inline — JWT
 * keys, `cookieSecret`, `encryptionKey` — because those are generated by the app and consumed by
 * every request (see `configSecrets.ts` for the `{SLUG}_*` env override of that fixed list). This
 * file is the other half of the pattern STACK.md calls "split": operator-provided third-party
 * credentials (external API keys, provider tokens, integration secrets) that have their own
 * lifecycle, differ per deployment, and grow without schema changes.
 *
 * The file is optional and gitignored (`/config/*.json`); its tracked companion is
 * `config/{slug}.secrets.json.example`, which declares the key shape with placeholder values
 * (`scripts/check-secrets-shape.ts` keeps the two in agreement). Contents are loaded once into a
 * module-level, deep-frozen namespace that is deliberately NOT merged into `AppConfig`: a value is
 * fetched at its use site via `getSecret()` / `resolveSecretRef()`, so it never rides along in
 * `getConfig()` to admin UIs, runtime snapshots, or audit details.
 *
 * Config fields ending in `Ref` (e.g. `oauth.github.clientSecretRef: "oauth.github.clientSecret"`)
 * are dot-path pointers into this namespace. `assertSecretRefsResolve()` runs at startup so a
 * dangling pointer fails fast rather than surfacing as a 500 the first time the feature is used.
 */

type SecretsNamespace = Readonly<Record<string, unknown>>;

interface SecretsFileStatus {
	/** Number of string leaves the file declared (never the values). */
	leafCount: number;
	/** Absolute path the loader looked at. */
	path: string;
	present: boolean;
}

interface DanglingSecretRef {
	configPath: string;
	ref: string;
}

let namespace: null | SecretsNamespace = null;
let status: null | SecretsFileStatus = null;

/** Freeze every object and array node reachable from `value` (strings and numbers need no freezing). */
function deepFreeze<T>(value: T): T {
	if (value !== null && typeof value === 'object') {
		for (const child of Object.values(value)) deepFreeze(child);
		Object.freeze(value);
	}
	return value;
}

/** True when every object/array node in `value` is frozen — the invariant `deepFreeze` establishes. */
function isDeepFrozen(value: unknown): boolean {
	if (value === null || typeof value !== 'object') return true;
	return Object.isFrozen(value) && Object.values(value).every(isDeepFrozen);
}

/**
 * Diagnostic for tests: whether the loaded namespace (including nested arrays) is deep-frozen. Returns
 * true before any file is loaded because an empty namespace has nothing to mutate.
 *
 * @returns true when every node of the namespace is frozen
 */
function isNamespaceDeepFrozen(): boolean {
	return namespace === null || isDeepFrozen(namespace);
}

/** Dot-paths of every string leaf, for diagnostics — paths only, values never leave this module. */
function collectLeafPaths(value: unknown, prefix = ''): string[] {
	if (!isPlainObject(value)) return [];
	const out: string[] = [];
	for (const [key, child] of Object.entries(value)) {
		const path = prefix ? `${prefix}.${key}` : key;
		if (isPlainObject(child)) out.push(...collectLeafPaths(child, path));
		else if (typeof child === 'string') out.push(path);
	}
	return out;
}

/**
 * Load `config/{slug}.secrets.json` if present. Called once from `initializeConfig()` as soon as the
 * slug is known; safe to call again (tests, config reload) — the namespace is replaced wholesale.
 *
 * A missing file is the normal case and is not an error. A file that exists but is not a JSON
 * object is a hard error: a half-loaded secrets namespace would make `*Ref` lookups fail in ways
 * that look like a typo in the ref rather than a broken file.
 */
function loadSecretsFile(
	slug: string,
	configDir: string = join(projectRoot, 'config'),
): SecretsFileStatus {
	const path = join(configDir, `${slug}.secrets.json`);
	if (!existsSync(path)) {
		// The normal case for most deployments — silent, so every script start does not announce it.
		namespace = Object.freeze({});
		status = { leafCount: 0, path, present: false };
		return status;
	}

	let parsed: unknown;
	try {
		parsed = JSON.parse(readFileSync(path, 'utf8'));
	} catch (err) {
		throw new Error(
			`Secrets file ${path} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
			{ cause: err },
		);
	}
	if (!isPlainObject(parsed)) {
		throw new Error(`Secrets file ${path} must contain a JSON object at the top level`);
	}

	namespace = deepFreeze(parsed);
	const leafCount = collectLeafPaths(namespace).length;
	status = { leafCount, path, present: true };
	configLogger.info({ leafCount, path }, 'Secrets file loaded');
	return status;
}

function ensureLoaded(): SecretsNamespace {
	if (namespace === null) {
		throw new Error('Secrets namespace not initialized. Call initializeConfig() first.');
	}
	return namespace;
}

/**
 * Look up a dot-path in the secrets namespace. Returns the string leaf, or `undefined` when the
 * path is absent or does not end at a string — callers that need the value use `requireSecret()`.
 */
function getSecret(path: string): string | undefined {
	let cursor: unknown = ensureLoaded();
	for (const segment of path.split('.')) {
		if (!isPlainObject(cursor)) return undefined;
		cursor = cursor[segment];
	}
	return typeof cursor === 'string' ? cursor : undefined;
}

function hasSecret(path: string): boolean {
	return getSecret(path) !== undefined;
}

function describeFile(): string {
	return status?.present ? status.path : 'config/{slug}.secrets.json (file not present)';
}

/** `getSecret()` that throws, naming the path and the file it expected it in — never the value. */
function requireSecret(path: string): string {
	const value = getSecret(path);
	if (value === undefined) {
		throw new Error(`Secret "${path}" is not defined in ${describeFile()}`);
	}
	return value;
}

/**
 * Resolve a `*Ref` config field at its use site. An empty ref means "not using the split pattern
 * for this field" and yields `undefined` so the caller can fall back to its inline value; a
 * non-empty ref must resolve (a dangling pointer is a misconfiguration, not a soft miss).
 */
function resolveSecretRef(ref: string | undefined): string | undefined {
	if (!ref) return undefined;
	return requireSecret(ref);
}

/** Dot-paths declared by the loaded file. Diagnostics and tests only; values are never exposed. */
function listSecretPaths(): string[] {
	return collectLeafPaths(ensureLoaded()).sort();
}

function getSecretsFileStatus(): null | SecretsFileStatus {
	return status;
}

/**
 * Walk a validated config and collect every non-empty `*Ref` string that does not point at a loaded
 * secret, as `configPath -> ref` pairs, so the caller can fail with all of them at once instead of
 * one restart per typo.
 */
function findDanglingSecretRefs(value: unknown, prefix = ''): DanglingSecretRef[] {
	if (!isPlainObject(value)) return [];
	const dangling: DanglingSecretRef[] = [];
	for (const [key, child] of Object.entries(value)) {
		const configPath = prefix ? `${prefix}.${key}` : key;
		if (isPlainObject(child)) {
			dangling.push(...findDanglingSecretRefs(child, configPath));
		} else if (key.endsWith('Ref') && typeof child === 'string' && child && !hasSecret(child)) {
			dangling.push({ configPath, ref: child });
		}
	}
	return dangling;
}

/** Startup guard: throw if any configured `*Ref` does not resolve in the secrets namespace. */
function assertSecretRefsResolve(config: Record<string, unknown>): void {
	const dangling = findDanglingSecretRefs(config);
	if (dangling.length === 0) return;
	const lines = dangling.map((d) => `  ${d.configPath} -> "${d.ref}"`).join('\n');
	throw new Error(
		`Config references ${String(dangling.length)} secret(s) missing from ${describeFile()}:\n${lines}\n` +
			'Add the key to the secrets file (see its .example companion) or clear the *Ref field.',
	);
}

export {
	assertSecretRefsResolve,
	findDanglingSecretRefs,
	getSecret,
	getSecretsFileStatus,
	hasSecret,
	isNamespaceDeepFrozen,
	listSecretPaths,
	loadSecretsFile,
	requireSecret,
	resolveSecretRef,
};
export type { DanglingSecretRef, SecretsFileStatus };
